apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "teamcity.fullname" . }}
  selector:
    matchLabels:
      {{- include "teamcity.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: teamcity-data
        {{- with .Values.dataStorage.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.dataStorage.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ .Values.dataStorage.size }}
        {{- if .Values.dataStorage.storageClass }}
        storageClassName: {{ .Values.dataStorage.storageClass }}
        {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "teamcity.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "teamcity.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-volume-owner
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data/teamcity_server/datadir"]
          volumeMounts:
              - name:  teamcity-data
                mountPath: /data/teamcity_server/datadir
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name:  teamcity-data
              mountPath: /data/teamcity_server/datadir
          env:
            - name: TEAMCITY_SERVER_MEM_OPTS
              value: "{{ .Values.teamcityJavaOpts }}"
          ports:
            - name: http
              containerPort: 8111
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /js/polyfills.js
              port: http
            initialDelaySeconds: 180
            failureThreshold: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /js/polyfills.js
              port: http
            initialDelaySeconds: 60
            failureThreshold: 10
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
