{{- if .Values.pvc.agent.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "teamcity.agentVolumeName" . }}
spec:
  storageClassName: {{ .Values.pvc.agent.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.agent.storageSize }}
{{- end }}