{{- if .Values.pvc.client.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ default (include "teamcity.fullname" .) }}-agent-data
spec:
  storageClassName: {{ .Values.pvc.client.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.client.storageSize }}
{{- end }}