apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "teamcity.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}
      release: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: server-data
        {{- if .Values.dataStorage.annotations }}
        {{- include ".Values.dataStorage.annotations" . | nindent 6 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.dataStorage.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ .Values.dataStorage.size }}
          {{- if .Values.dataStorage.storageClassName }}
        storageClassName: {{ .Values.dataStorage.storageClassName }}
          {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-volume-owner
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data/teamcity_server/datadir"]
          volumeMounts:
              - name:  server-data
                mountPath: /data/teamcity_server/datadir
      containers:
        - name: {{ template "teamcity.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name:  server-data
              mountPath: /data/teamcity_server/datadir
          ports:
            - name: {{ template "teamcity.name" . }}-http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.readinessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
{{- end }}
{{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.livenessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{    toYaml . | indent 8 }}
{{- end }}
{{- with .Values.server.affinity }}
      affinity:
{{    toYaml . | indent 8 }}
{{- end }}
{{- with .Values.server.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
    {{- end }}
