apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.version }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
          - name: server-data
            persistentVolumeClaim:
              claimName: {{ template "teamcity.serverVolumeName" . }}
      containers:
        - name: {{ template "teamcity.fullname" . }}
          image: {{ .Values.server.image.repository }}:{{ default "latest" .Values.server.version }}
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          volumeMounts:
            - name:  server-data
              mountPath: /data/teamcity_server/datadir
          ports:
            - name: {{ .Release.name }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
{{- if .Values.server.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.readinessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
{{- end }}
{{- if .Values.server.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.livenessProbe.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
{{- end }}
          resources:
{{  toYaml .Values.server.resources | indent 12 }}
{{- with .Values.server.nodeSelector }}
      nodeSelector:
{{    toYaml . | indent 8 }}
{{- end }}
{{- with .Values.server.affinity }}
      affinity:
{{    toYaml . | indent 8 }}
{{- end }}
{{- with .Values.server.tolerations }}
      tolerations:
{{    toYaml . | indent 8 }}
{{- end }}
