{{- if .Values.ingress.enabled -}}
{{-   $serviceName := include "teamcity.fullname" . -}}
{{-   $servicePort := "http" -}}
{{-   $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ template "teamcity.name" . }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{-   if .Values.ingress.labels }}
{{      .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{-   end}}
{{-   if .Values.ingress.annotations }}
annotations:
{{      .Values.ingress.annotations | toYaml | trimSuffix "\n" | indent 4 -}}
{{-   end }}
spec:
{{-   if .Values.ingress.defaultBackend.enabled }}
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
{{-   end -}}
{{-   if .Values.ingress.hosts }}
  rules:
{{-     range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
{{-     end -}}
{{-   end -}}
{{-   if .Values.ingress.tls }}
tls:
{{      toYaml .Values.ingress.tls | indent 4 }}
{{-   end -}}
{{- end -}}
