{{- if .Values.pvc.server.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "teamcity.serverVolumeName" . }}
spec:
  storageClassName: {{ .Values.pvc.server.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.server.storageSize }}
{{- end }}