{{- if .Values.pvc.server.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "teamcity.serverVolumeName" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    version: {{ .Values.server.image.version }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{-   if .Values.pvc.server.storageClass }}
  storageClassName: {{ .Values.pvc.server.storageClass }}
{{-   else }}
  storageClassName: default
{{-   end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.server.storageSize }}
{{- end }}