apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamcity.fullname" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{-   range $key, $val := .Values.service.annotations }}
{{      $key | indent 4 }}: {{ $val | quote }}
{{-   end}}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "teamcity.selectorLabels" . | nindent 4 }}
