apiVersion: v1
kind: Service
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    chart: {{ template "teamcity.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.artifactory.service.annotations }}
  annotations:
{{   toYaml .Values.artifactory.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Release.Name }}
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "teamcity.name" . }}
    release: {{ .Release.Name }}
